alias SSMPortForwarding='(curr_dir="$(pwd)"; cd /etc/ssm-port-forwarding && ./SSMPortForwarding.sh; cd "$curr_dir")'
alias air='$(go env GOPATH)/bin/air'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias motus_clean='catkin_make clean -C /home/daventor/ws_motus; rm -rf /home/daventor/ws_motus/build/ /home/daventor/ws_motus/devel/'
alias motus_debug='catkin_make -DCMAKE_BUILD_TYPE=Debug -C /home/daventor/ws_motus'
alias motus_release='catkin_make -DCMAKE_BUILD_TYPE=Release -C /home/daventor/ws_motus'
alias rosremote='export ROS_MASTER_URI=http://${MOTUS}:11311; export ROS_HOSTNAME=${MOTUS}'
alias sshpi='ssh turtlebot@192.168.10.1'
alias ws_motus='source /home/daventor/ws_motus/devel/setup.bash'
